# Generated by Django 4.2.13 on 2024-07-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profilemodel_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='avatar',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
