# Generated by Django 4.2.14 on 2024-08-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_profilemodel_alias"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilemodel",
            name="websocket",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
