# Generated by Django 4.2.13 on 2024-10-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profilemodel_online_blockmodel_noticemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='match_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
