# Generated by Django 4.2.13 on 2024-11-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profilemodel_match_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticemodel',
            name='data',
            field=models.CharField(max_length=10240),
        ),
    ]
