# Generated by Django 4.2.13 on 2024-08-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profilemodel_avatar'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='lobbies', to='profiles.profilemodel'),
        ),
    ]
