# Generated by Django 4.2.13 on 2024-08-22 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profilemodel_avatar'),
        ('tournament', '0002_lobby_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='is_tournament_started',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.lobby')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='profiles.profilemodel')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='profiles.profilemodel')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='profiles.profilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='tournament.lobby')),
                ('matches', models.ManyToManyField(related_name='brackets', to='tournament.match')),
            ],
        ),
    ]
