# Generated by Django 5.0.7 on 2024-08-28 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profilemodel_alias'),
        ('tournament', '0003_lobby_is_tournament_started_match_bracket'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lobbies', to='profiles.profilemodel'),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='max_players',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player1', to='profiles.profilemodel'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player2', to='profiles.profilemodel'),
        ),
    ]
