# Generated by Django 4.2.13 on 2024-07-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
    ]
