# Generated by Django 5.0.6 on 2024-08-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_remove_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_oauth_user',
            field=models.BooleanField(default=False),
        ),
    ]
